### ISSUE TITLE
Can hector_ui work for Ros Melodic (Ubuntu 18.04)

### ISSUE THREAD

**Issue by anastaga** [RAFALAMAO/hector-quadrotor-noetic#6]
Hello and thanks for your work in this repository. I was wondering if hector_ui to control the drone can work on Ros Melodic, tried it but i got some errors.
1) tkinter wasn't installed. I did install it but then
2) I got this error
Traceback (most recent call last):
  File "/home/anast/catkin_ws/src/hector_ui/src/ui_hector_quad.py", line 10, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'

**Comment by RAFALAMAO** [comment]
The is happens because Melodic works with Python2 and Noetic with Python3, so, you need to port de code to Python2 or, create a package or workspace in Melodic where you can run Python3 nodes.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: anastaga ***@***.***>
Sent: Tuesday, July 5, 2022 3:49:31 AM
To: RAFALAMAO/hector-quadrotor-noetic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RAFALAMAO/hector-quadrotor-noetic] Can hector_ui work for Ros Melodic (Ubuntu 18.04) (Issue #6)


Hello and thanks for your work in this repository. I was wondering if hector_ui to control the drone can work on Ros Melodic, tried it but i got some errors.

  1.  tkinter wasn't installed. I did install it but then
  2.  I got this error
Traceback (most recent call last):
File "/home/anast/catkin_ws/src/hector_ui/src/ui_hector_quad.py", line 10, in
import rospy
File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/init.py", line 49, in
from .client import spin, myargv, init_node,
File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in
import roslib
File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/init.py", line 50, in
from roslib.launcher import load_manifest # noqa: F401
File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in
import rospkg
ModuleNotFoundError: No module named 'rospkg'
